### PR TITLE
Atomic operation

### PR DESCRIPTION
**Pull request by naterush**
# Changes

This adds a basic error handling function for merge. If merge throws an error during execution, then if there has been a commit on the personal branch since the commit started, we revert to that commit. If there has been no commit on the personal branch, we don't need to revert, because a new commit on personal is the first thing that happens in the merge.

I tested by throwing errors between most lines in merge. Please check by doing the same. But it is fragile, and long term I'd like a better solution.

- [x] I ran all the tests to make sure I didn't break anything.

### CODE REVIEW

**Comment by aarondr77** [comment]
I don't think this is working. I added an error right before "tmpSheet.delete();" in merge - the error screen was rendered, but it did not revert my state. I still have the saga-tmp file.

**Comment by naterush** [comment]
@aarondr77 yep. I'll get this sorted after the lint PR.

**Comment by naterush** [comment]
My bad - should have labeled it WIP!

**Comment by naterush** [comment]
@aarondr77 check this out when you get the chance. I think merge should be atomic now; it will either merge your things, or it will not change your personal branch. But not sure about other operations -- should I handle those here as well? I'd be down to get this merged, and break the other error handling for operations into other functions.

In any case, a review here would be appreciated. Wanna make sure my approach seems reasonable for now.

**Comment by aarondr77** [comment]
This looks good to me.

**Pull request merged**
