### PR TITLE
Demo mode

### PR DESCRIPTION
**Pull request by naterush**
# Changes

This adds demo mode to the app. To do so, it introduces a new context (which is a global state store that is accessible in any functional react component), and then changes the dev screen so it's a functional component and can actually consume this context easily. 

When testing this, please make sure:
1. Demo mode works, as described in the testing documentation (does it belong in the testing documentation?).
2. Nothing else on the dev screen broke.

The code here is a bit wonky - or at the very least, I don't totally understand what I've written. `useEffect` is def confusing. IMO, we should take out the technical debt if it's working and pay it back as we begin to understand React hooks better. @aarondr77 let me know one morning when you are free, and we can set up 30 minutes to walk through the code -- but let's merge before that (if you test it and it's functionally working). 

- [x] I ran all the tests to make sure I didn't break anything.

### CODE REVIEW

**Comment by aarondr77** [comment]
If I run demo mode and hit the advance button more times than there are steps and then run a test suite afterwards, all the tests will fail. 


Similarly, if I overrun the scenario and then try to merge, merge does not operate correctly. It gets hung on the "Merging .. please do not edit" screen. With the below console:

I think this is worth fixing because we want to eliminate the possibility of our tool looking broken in demos. 

Screen Shot 2020-06-10 at 8 31 08 PM

**Comment by aarondr77** [comment]
The create sharing link functionality is not working. If I hit that button, then look at the saga sheet, I see the below. 

Screen Shot 2020-06-12 at 3 13 47 PM

**Comment by aarondr77** [comment]
It would be nice to have named steps which the button would show, so when we are demoing the tool, we know what we are about to do. Again, trying to reduce chances of us fucking up the demo.

**Comment by aarondr77** [comment]
Also, can you add to the documentation information about if/when the demoer should fill in their email. Or do we just go straight to loading the scenario?

**Comment by naterush** [comment]
@aarondr77 good catch. This was a result of changing the APIs up - and not integrating that in to this branch. Just merged that into this branch.

As far as a) describing the scenario and b) naming the steps, I think this is a good feature. Let's leave that to a different PR to get this merged in if it's good. I opened an issue.

**Comment by aarondr77** [comment]
Dope. It looks good. Merging.

**Pull request merged**
