### PR TITLE
[WIP] added formatting tests

### PR DESCRIPTION
**Pull request by aarondr77**
# Changes

- [ ] I ran all the tests to make sure I didn't break anything.

### CODE REVIEW

**Comment by aarondr77** [comment]
@naterush while I was writing these tests, I noticed that after running our tests, only the active sheets remain in the workbook. If I recreate the test in Excel manually, the hidden sheets are still there.

**Comment by naterush** [comment]
@aarondr77 this was added in the testing PR. We cleanup after tests now. It does make sense you might want to put yourself in a specific state, but generally I was thinking of this as a dev dashboard + scenarios thing.

If it'd be valuable, we can probably add a config that lets you not cleanup after a specific test, but it might be more work than it's worth.

**Comment by aarondr77** [comment]
ahh okay. No this is okay. I just didn't realize that was happening and thought there was a bug somewhere. thx.

**Comment by naterush** [comment]
Merge whenever, if you're finished.

**Pull request merged**
