### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by naterush**
# Changes

This makes it so the taskpane reloads your state when your reopen a saga project. Also some misc. cleanup. 

This is what remains of the poor logging PR.

- [x] I ran all the tests to make sure I didn't break anything.

### CODE REVIEW

**Comment by naterush** [comment]
@aarondr77 LGTM?

**Comment by aarondr77** [comment]
Sorry - I should have gotten to this sooner. 

The intended functionality is not occurring though. 

Bug 1 - If I create a saga project, save it,  close excel, reopen the workbook, then click on create saga project, it takes me to the input your email screen. 

Bug 2 -  If I create a saga project, save it,  close excel, reopen the workbook, then the share project button, it opens the taskpane in the developer window and also opens an empty taskpane in the correct location. In the developer window, it opens to the shared screen, but with no URL in the share URL box. 

Relatedly, if I do the above but click the create saga project button first, then the developer window does not open, the share project button renders in the taskpane, but there is still no link.

**Comment by naterush** [comment]
@aarondr77 bug 2 is something that exists outside the context of this PR. Not sure how to fix it currently. Opening an issue for new window now.

Bug 1 should be fixed, and all tests passing, so please check this out, when you get the chance.

**Comment by aarondr77** [comment]
There is one small bug where the screen flashes the email signup page before redirecting to the sharing link. But I think it's okay for now. 

I tried to resolve the merge conflicts and merge in the PR, but this code is very fragile and I'm not sure what I am doing wrong. Can you give it a try?

**Comment by naterush** [comment]
@aarondr77 no way around the flicker; we have to wait until the Excel javascript API loads before we can request the data to know if a saga project is initialized, and that usually takes a second.

**Comment by naterush** [comment]
Squashed the merge conflicts, tests passing. Merging.

**Pull request merged**
